### ISSUE TITLE
Feature: User can search for a recipe

### ISSUE THREAD

**Issue by max-cendalski** [max-cendalski/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

![issue1](https://user-images.githubusercontent.com/25681013/142549331-e0742147-ce7a-47e8-8735-0d971c4306f7.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add Div [Data-View="Entry-Form"] to HTML 
- [x] Add Form(and style)
- [x] Add Select(and style, only first input is required)
- [x] Create Object for data from API
- [x] Render Data( create DOM tree)
- [x] Add [Data-view="Results"]
-
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by max-cendalski** [comment]
![user-can-search-for-a-recipe](https://user-images.githubusercontent.com/25681013/142707398-862ac587-fb28-4422-a77d-64913d1e68aa.gif)
