### ISSUE TITLE
Feature: User can define nutrition content for searched recipes

### ISSUE THREAD

**Issue by max-cendalski** [max-cendalski/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![User can define nutrition content for searched recipes](https://user-images.githubusercontent.com/25681013/142707619-fcaa10ae-a458-45ff-8779-f7277c707600.jpg)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Add event listener for form select element, add variables to store input data for all 4 nutrition
- [x] Add function to render DOM Tree for inputs with specify amount of  sugar, protein, carbs
- [x] Toggle calories inputs ?
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
